api_controllers:
    resource: ../src/Presentation/Controller/Api/
    type: attribute

ui_controllers:
    resource: ../src/Presentation/Controller/  # ou le dossier où est ton controller qui rend le template
    type: attribute