login:
    path: /api/login
    methods: [POST]

api_controllers:
    resource: ../src/Presentation/Controller/API/
    type: attribute

ui_controllers:
    resource: ../src/Presentation/Controller/
    type: attribute
    exclude:
        - ../src/Presentation/Controller/API/

api_client_nouveau:
    resource: ../src/Presentation/Controller/API/Client/
    type: attribute