# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    # Valeurs scalaires uniquement ici

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    # Binding interface → implémentation concrète
    App\Domain\Utilisateur\Repository\UtilisateurRepositoryInterface:
        alias: App\Infrastructure\Persistance\Doctrine\Repository\UtilisateurRepository

    # Plus besoin de définir manuellement CreateUtilisateurUseCase
    # car autowire: true le résout automatiquement grâce à l'alias ci-dessus