# config/services.yaml
# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    # Valeurs scalaires uniquement ici

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Presentation\Controller\API\UtilisateurController:
        class: 'App\Presentation\Controller\API\UtilisateurController'
        tags: ['controller.service_arguments']

    # Binding interface → implémentation concrète
    App\Domain\Utilisateur\Repository\UtilisateurRepositoryInterface:
        class: App\Infrastructure\Persistance\Doctrine\Repository\UtilisateurRepository
        tags: ['doctrine.repository_service']